version: "3"

services:
  app:
    build: .
    container_name: node-zhay
    command: npm run start
    depends_on:
      - mysql
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

  mysql:
    container_name: mysql-zhay
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
    expose:
      - 3306
    image: mysql:latest
    ports:
      - 3306:3306
    # restart: always
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/

volumes:
  db-config:
  db-data:
